version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-power-search
    volumes:
      - mysql-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: power_search_db
    ports:
      - '3307:3306'
  postgres:
    image: "postgres:latest"
    container_name: postgres
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  mysql-db:
  postgres-db:
